<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[FF Launched Browser sucessfully]]>
    </line>
    <line>
      <![CDATA[URL entered success fully]]>
    </line>
    <line>
      <![CDATA[Browser closed sucessfully]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="16119" started-at="2018-04-01T04:19:21Z" finished-at="2018-04-01T04:19:37Z">
    <groups>
    </groups>
    <test name="Test_ff" duration-ms="16119" started-at="2018-04-01T04:19:21Z" finished-at="2018-04-01T04:19:37Z">
      <class name="scripts.TestScript_02">
        <test-method status="PASS" signature="launchBrowser(org.testng.xml.XmlTest)[pri:0, instance:scripts.TestScript_02@2a556333]" name="launchBrowser" is-config="true" duration-ms="6655" started-at="2018-04-01T04:19:21Z" finished-at="2018-04-01T04:19:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.xml.XmlTest@b1558eff]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[FF Launched Browser sucessfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="login()[pri:0, instance:scripts.TestScript_02@2a556333]" name="login" is-config="true" duration-ms="7790" started-at="2018-04-01T04:19:28Z" finished-at="2018-04-01T04:19:36Z">
          <reporter-output>
            <line>
              <![CDATA[URL entered success fully]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="test_verifySuccessfullLogin()[pri:0, instance:scripts.TestScript_02@2a556333]" name="test_verifySuccessfullLogin" duration-ms="1513" started-at="2018-04-01T04:19:36Z" finished-at="2018-04-01T04:19:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Username or Password is invalid. Please try again..] but found [Username or Password is invalid. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Username or Password is invalid. Please try again..] but found [Username or Password is invalid. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pom.Login.verifyErrorMsg(Login.java:54)
at scripts.TestScript_02.test_verifySuccessfullLogin(TestScript_02.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_verifySuccessfullLogin -->
        <test-method status="PASS" signature="logout()[pri:0, instance:scripts.TestScript_02@2a556333]" name="logout" is-config="true" duration-ms="1" started-at="2018-04-01T04:19:37Z" finished-at="2018-04-01T04:19:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:scripts.TestScript_02@2a556333]" name="closeBrowser" is-config="true" duration-ms="140" started-at="2018-04-01T04:19:37Z" finished-at="2018-04-01T04:19:37Z">
          <reporter-output>
            <line>
              <![CDATA[Browser closed sucessfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- scripts.TestScript_02 -->
    </test> <!-- Test_ff -->
  </suite> <!-- Suite -->
</testng-results>
